services:
  app: # app 이하 코드를 도커 이미지 빌드 후 추가!
    image: backend-app:local
    container_name: backend-app-dev
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - backend-mysql
    restart: unless-stopped
  backend-mysql:
   image: mysql:8.0.43
   container_name: backend-mysql-dev
   environment:
     MYSQL_ROOT_PASSWORD: wjddms0621@
     MYSQL_DATABASE: backend-db
     MYSQL_USER: backend
     MYSQL_PASSWORD: wjddms0621@
     TZ: Asia/Seoul
   command: [
     "--default-authentication-plugin=caching_sha2_password",
     "--character-set-server=utf8mb4",
     "--collation-server=utf8mb4_unicode_ci"
   ]
   ports:
     - "3306:3306"
   volumes:
     - ./_vol/mysql:/var/lib/mysql